@url = http://localhost:3000

### Request
GET {{url}}/estudo/req

### Response Express
GET {{url}}/estudo/resExpress

### Response
GET {{url}}/estudo/res

### Next
GET {{url}}/estudo/next

### Session
GET {{url}}/estudo/session

### Param
GET {{url}}/estudo/param/1

### Body
GET {{url}}/estudo/body
Content-Type: application/json

{
  "braco": true,
  "perna": true,
  "cabeca": true
}

### Query
GET {{url}}/estudo/query
  ?cachorro=teca
  &gato=miau

### Headers
GET {{url}}/estudo/headers
Authorization: Bearer 123456

### Ip
GET {{url}}/estudo/ip

### Host Param
GET {{url}}/estudo/hostParam

### Wild Card
GET {{url}}/estudo/ab.-.cd

### Promise
GET {{url}}/estudo/promise

### Observable
GET {{url}}/estudo/observable

### Cat Create
POST {{url}}/cats
Content-Type: application/json

{
  "name": "Celina 3",
  "age": 1,
  "breed": "RAG_DOLL"
}

### Cat Find All
GET {{url}}/cats